project_name: mindscript

builds:
  - id: msg
    main: ./cmd/msg
    binary: msg
    env: [CGO_ENABLED=1]
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags: ["-s -w"]
  - id: msg-lsp
    main: ./cmd/msg-lsp
    binary: msg-lsp
    env: [CGO_ENABLED=1]
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags: ["-s -w"]

archives:
  - id: tgz
    format: tar.gz
    name_template: "mindscript-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - VERSION
      - docs/**
      - data/**
      - examples/**
      - lib/**
    # Put binaries under bin/ inside the archive
    wrap_in_directory: true
    files_info:
      strip_parent: true
    # Place binaries into bin/ (GoReleaser does this via replacements below)
    replacements:
      darwin: darwin
      linux: linux
      amd64: amd64
      arm64: arm64

checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256

release:
  prerelease: auto
